### ISSUE TITLE
Close popup with a button from the content.

### ISSUE THREAD

**Issue by micjohnson382** [niutech/showModalDialog#15]
I am able to close the popup using the X on the top right corner. I am trying to close the popup a thru a "Close" button from the iframe  dialog-body content. I tried using removeChild function but failed.

I have tried with "self.parent.document.getElementsByTagName('dialog')[0].close()" but got this error "Uncaught TypeError: Cannot read property 'close' of undefined"

How do I do that? Appreciate your help.

**Comment by micjohnson382** [comment]
I found the soultion thru this link.

https://github.com/niutech/showModalDialog/issues/5 

But not sure what to do If my calling and the popup pages are located in different folders. I am getting "Uncaught TypeError: Cannot read property 'close' of undefined" error.

**Comment by niutech** [comment]
The directory should not matter, as long as the modal and the parent document are in the [same origin](https://en.wikipedia.org/wiki/Same-origin_policy). Then you should be able to acces the parent document from inside the modal using:

``` JS
var parentDoc = parent.document;
var dialogElms = parentDoc.getElementsByTagName('dialog');
var firstDialog = dialogElms[0];
firstDialog.close();
```

If you get a TypeError, it means that the `dialogElms` is empty.

**Comment by micjohnson382** [comment]
Thank you very much for your reply. Yes I am getting a TypeError. I did check the length of dialogElms and it returned 0. I am using the exact code given here and Not sure why I am getting zero length.

**Comment by niutech** [comment]
Open Dev Tools and inspect the code provided. Check if `parentDoc` points to the parent document, and if it contains a `<dialog>` element. Also check if replacing `parent` with `top` will work.

**Comment by micjohnson382** [comment]
Thank you very much. The code is working well after I added "parent." to reach my popup root level.
var parentDoc = <strong>parent</strong>.parent.document;
Appreciate your help.

**Comment by Zolfaghari** [comment]
to close from modal form:
parent.document.getElementById('dialog-close').click();
