### ISSUE TITLE
Is i t possible to support Microsoft Edge? 

### ISSUE THREAD

**Issue by benlin51** [niutech/showModalDialog#17]
Edge does not work on your demo url. 
IE just only works on eval version of your demo.

**Comment by niutech** [comment]
The first method uses generators, which are supported in Microsoft Edge
with experimental JavaScript features enabled (about:flags).

> The second method should work fine.

**Comment by msmuthu3** [comment]
Hi , whether this pauses JS execution as the original showmodaldialog do ?

**Comment by niutech** [comment]
Yes it does, by using `yield` or throwing an Exception.

**Comment by jwcGitHub** [comment]
Even with experimental features enabled I was not able to get edge to work properly with this demo. It has been over a year since issue was originally raised. Maybe Edge has changed? The version  is 
Microsoft Edge 40.15063.674.0
Edge HTML 15.15063

**Comment by niutech** [comment]
Edge does not support the `<dialog>` element. See #27.
