### ISSUE TITLE
window.close() can't be used

### ISSUE THREAD

**Issue by W65138497** [niutech/showModalDialog#20]
window.close() don't used

**Comment by niutech** [comment]
What do you mean?

**Comment by W65138497** [comment]
"window.close()" cannot be used

**Comment by niutech** [comment]
No, but you can type `parent.document.getElementsByTagName('dialog')[0].close();` to close the dialog from inside.

**Comment by W65138497** [comment]
Yes, I did the same，Thanks！

soft_for_java@163.com

From: niu tech
Date: 2016-08-31 06:57
To: niutech/showModalDialog
CC: W65138497; Author
Subject: Re: [niutech/showModalDialog] window.close() can't be used (#20)
No, but you can type parent.document.getElementsByTagName('dialog')[0].close(); to close the dialog from inside.
