### ISSUE TITLE
Closing the Modal through button click

### ISSUE THREAD

**Issue by VanishreeKS** [niutech/showModalDialog#22]
I have to close the Modal Dialog from the button click event present in the page loaded in the IFrame. How do I do this. I have used your code for ShowModalDialog.
Everything works fine in IE, however in chrome I am unable to pass the value selected to parent window from ShowModalDialog and close the window through close button.
Kindly help.

**Comment by niutech** [comment]
See issue #5.
You can pass back the value setting `window.returnValue` in the modal page, provided that they are in the same domain.
