### ISSUE TITLE
Need to open dialog in a new tab and chrome browser

### ISSUE THREAD

**Issue by tejareddy457** [niutech/showModalDialog#25]
Hi,

Code working fine and great !!!!!!!!

Actually dialog box opens inside the tab but we need dialog box should open in a new tab. In IE it works opening in a new tab.

Could you please help on this issue

**Comment by tejareddy457** [comment]
Any comments please

**Comment by tejareddy457** [comment]
How can i open same dialog outside frame or frameset ..? Could you please help

**Comment by niutech** [comment]
You can just use `window.open()` in such case. There is no other way to open a modal dialog in a new tab.
