### ISSUE TITLE
Uncaught Execution stopped until showModalDialog is closed

### ISSUE THREAD

**Issue by venkatramireddy** [niutech/showModalDialog#26]
Getting this error, I put YES or NO buttons in dialogue and returned the values with window.returnValue (0 or 1)

**Comment by avnishv** [comment]
Even I'm facing same issue. Any solution??

**Comment by derhecht** [comment]
As fas as I understand the code this is just a hint not a typical exception.

**Comment by niutech** [comment]
This is working as intended - the Exception is thrown in order to stop execution of the JS code until the modal dialog is closed.
