### ISSUE TITLE
demo.html doesn't work correctly on Edge browser

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [niutech/showModalDialog#27]
Demo.html doesn't work correctly on Edge(Microsoft Edge 38.14393.1066.0 under Win10)- dialogs shown below, not as popup.

Also on IE (Ver 11.1066) "yeild" button does nothing (but "eval" works as expected)

**Comment by niutech** [comment]
This is because [Edge does not support](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/dialogelementformodals/) `<dialog>` element yet and IE11 does not support JS generators. Please use the `<dialog>` [polyfill](https://github.com/GoogleChrome/dialog-polyfill).
