### ISSUE TITLE
Not work with Firefox

### ISSUE THREAD

**Issue by Jim25** [niutech/showModalDialog#29]
Lib and Demo code not work with Firefox.

**Comment by niutech** [comment]
This is due to [HTMLDialogElement.showModal()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal#Browser_compatibility) being disabled by default in Firefox. You can enable it by setting `dom.dialog_element.enabled` to `true` in _about:config_.
