### ISSUE TITLE
caller property is null

### ISSUE THREAD

**Issue by andekande** [niutech/showModalDialog#3]
I am calling showModalDialog inside of a function that is part of a module pattern. In this scenario showModalDialog.caller property is null and the polyfill breaks.

**Comment by even0220** [comment]
var caller = showModalDialog.caller.caller.toString();

**Comment by rostacik** [comment]
it seems to me, that the problem is caused by calling showModalDialog using function that is defined on "use strict"; context. if I removed "use strict" shim is working. if you want, I can post some example. tested with Chrome Version 45.0.2414.0 canary (64-bit)

**Comment by andekande** [comment]
in my case the "use strict" declaration is and was indeed present

**Comment by niutech** [comment]
I assume it is already resolved.
