### ISSUE TITLE
Issue in Firefox

### ISSUE THREAD

**Issue by VanishreeKS** [niutech/showModalDialog#31]
An error occurs in FF saying dialog.showmodal is not a function.
The version of FF is 56.

Please suggest what is the alternate way.

**Comment by niutech** [comment]
As stated in the README, the `dom.dialog_element.enabled` preference have to be set to true in `about:config` or the dialog-polyfill has to be used instead.

**Comment by VanishreeKS** [comment]
How do I the changes in about:config on server?. It will be difficult to ask the customers to do the change in the about:config. Please help

**Comment by niutech** [comment]
Have you tried using the [dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill)?

You can track the progress of Firefox in [this Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=840640).
