### ISSUE TITLE
Firefox latest version Dialog window not opening

### ISSUE THREAD

**Issue by VanishreeKS** [niutech/showModalDialog#32]
Hi, Thanks for the reply for my previous post. I changed the flag of Dom.dialog.element to True.
Still the page which I want to open is not opening. I checked the Popup blocker..its not checked..allows popup.
The page executes the code of called popup page. But it won't bring up the popup page.
Its not throwing any error. What might be the issue. Please help.

**Comment by VanishreeKS** [comment]
How do I the About:config on server. This change is difficult to do in each client machine. Is there any one place where we can make this change?.

**Comment by grahamperrin** [comment]
> … Dom.dialog.element to True.
> Still the page which I want to open is not opening. …

about:config?filter=dom.dialog

I have only `dom.dialog_element.enabled`, `false` by default, with Waterfox 56.2.0.31_5 on FreeBSD-CURRENT. YMMV. 

With the one boolean switched to `true`, both buttons at http://niutech.github.io/showModalDialog/demo.html result in a dialogue. 

Maybe useful: 

- [Experimental features in Firefox - Mozilla | MDN](https://developer.mozilla.org/Firefox/Experimental_features)

**Comment by niutech** [comment]
Thanks @grahamperrin for the explanation!
