### ISSUE TITLE
Edge browser error

### ISSUE THREAD

**Issue by marcusbecker** [niutech/showModalDialog#35]
On the Edge the modal, using the parameter below, shows up after all content making the page scroll. 
Example: window.showModalDialog( "teste.html", "", "dialogTop:10; dialogLeft:0; dialogWidth:795px; dialogHeight:585px; dialogResizable:no; scroll:no; status:no" );

Obervation, my page was opened with windo.open.

**Comment by niutech** [comment]
Edge does not support native `showModalDialog` nor `<dialog>` element. You have to use the [dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill)
