### ISSUE TITLE
how to make the dialog scrollable?

### ISSUE THREAD

**Issue by chengfanke** [niutech/showModalDialog#36]
Thanks for the great job. I just wonder how can I add scrollbar to the dialog, if the content height is beyond the dialog size. Can someone give me any clue?

**Comment by niutech** [comment]
You can add `overflow: auto;` to the CSS styles of the `<dialog>` element (e.g. using the `options` argument in `showModalDialog()`)

**Comment by chengfanke** [comment]
thx for the reply. I have have a try.
