### ISSUE TITLE
JavaScript from modal window is not executed

### ISSUE THREAD

**Issue by apuchkov** [niutech/showModalDialog#4]
Any plans to add this functionality?

**Comment by niutech** [comment]
Exactly which JS isn't executed? Could you give an example?

**Comment by apuchkov** [comment]
I think any JavaScript used inside the page which is opened as a modal is not executed. 

Either form external JavaScript files referenced via <script > or embedded JS inside <script> tag

**Comment by niutech** [comment]
The modal page is loaded inside an `<iframe>` so any JS is executed.
