### ISSUE TITLE
trying to close the dialog from a button

### ISSUE THREAD

**Issue by markusdf** [niutech/showModalDialog#5]
Hi there, The script is great, and does almost everything I need, except that I cant seem to close the dialog from a button within the modal dialog.

the dialog is a dynamic table of scrolling data which works fine, but i can't seem to get the "window.close()" functionality to trigger from inside the dialog. I've tried everything I can think of. any pointed on how to fire the close without clicking the x?

**Comment by niutech** [comment]
To close the dialog, invoke: `parent.document.getElementsByTagName('dialog')[0].close();` provided that both pages are on the same domain.

**Comment by micjohnson382** [comment]
Please help me to fix what If my calling page and the popup page are located in different folders. I am getting "Uncaught TypeError: Cannot read property 'close' of undefined" error.
