### ISSUE TITLE
close directly after clicking on a link on the window

### ISSUE THREAD

**Issue by youmnah** [niutech/showModalDialog#6]
Hi, this JavaScript is working well on chrome but i want the window to close directly after choosing an option or clicking on a link instead of manually closing the window.
Thanks in advance.

**Comment by niutech** [comment]
Have a look at the issue #5.

**Comment by youmnah** [comment]
It didn't work

**Comment by niutech** [comment]
What exactly didn't work? Try adding this code to your modal.html:
`<input type="button" value="Close modal" onclick="parent.document.getElementsByTagName('dialog')[0].close();">`

**Comment by youmnah** [comment]
Thank you it works now :)
