### ISSUE TITLE
Nested Functions

### ISSUE THREAD

**Issue by anuj1537** [niutech/showModalDialog#7]
If a nested function calls showmodaldialog how do I continue execution till the end. Eg function1 calls function2 which calls function3 where show modal dialog is called.  Using the caller property only function3 is executed but function2 and function1 execution does not complete. Caller.caller won't help me as I never know how many levels the function is nested.

Thanks
Anuj

**Comment by niutech** [comment]
In that scenario, try refactoring the innermost function so that it invokes another function after getting the data returned from showModalDialog:

``` JS
function innermostFun() {
    var result = showModalDialog(...);
    outerFun(result);
}
```
